/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dlgBuscarAlumno.java
 *
 * Created on 27-ene-2012, 9:45:17
 */
package Formularios;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import Controladores.ctrlAlumnos;
import Controladores.ctrlKardex;
import Entidades.Alumnos;
import Entidades.ReporteHistorialAcademico;
import Reportes.JRDHistorialAcademicoAlumno;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Last Develop
 */
public class dlgBuscarAlumnokardex extends javax.swing.JDialog {

    private String texto = "";
    private ctrlAlumnos ctrlalumno = new ctrlAlumnos();
    private ArrayList<Alumnos> lista = null;
    private Alumnos objalumno;

    /** Creates new form dlgBuscarAlumno */
    public dlgBuscarAlumnokardex(java.awt.Frame parent, boolean modal) throws SQLException, ClassNotFoundException {
        super(parent, modal);
        initComponents();
        this.jLabel3.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCampo = new javax.swing.JComboBox();
        txtCriterio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditarKardex = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscar Alumno");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        jLabel1.setText("Buscar:");

        jLabel2.setText("Por:");

        cmbCampo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Nombre", "Matricula", "Apellido Paterno", "Apellido Materno" }));
        cmbCampo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCampoItemStateChanged(evt);
            }
        });
        cmbCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCampoActionPerformed(evt);
            }
        });

        txtCriterio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCriterioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCriterioKeyReleased(evt);
            }
        });

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(cmbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAlumnos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btnAgregar.setText("Crear");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditarKardex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnEditarKardex.setText("Editar");
        btnEditarKardex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarKardexActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/printer.png"))); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarKardex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditarKardex)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtCriterioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCriterioKeyPressed
    // TODO add your handling code here:
}//GEN-LAST:event_txtCriterioKeyPressed

private void txtCriterioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCriterioKeyReleased
    // TODO add your handling code here:
    objalumno = new Alumnos();
    objalumno.setNombre(txtCriterio.getText());
    texto = this.cmbCampo.getSelectedItem().toString();

    lista = ctrlalumno.getBuscarAlumnos(objalumno, texto);
    this.jLabel3.setText(String.valueOf(lista.size()));
    this.tablaAlumnos.setModel(ctrlalumno.getPersonal(lista));

    tablaAlumnos.getColumnModel().getColumn(0).setMaxWidth(0);
    tablaAlumnos.getColumnModel().getColumn(0).setMinWidth(0);
    tablaAlumnos.getColumnModel().getColumn(0).setPreferredWidth(0);

    tablaAlumnos.getColumnModel().getColumn(5).setMaxWidth(0);
    tablaAlumnos.getColumnModel().getColumn(5).setMinWidth(0);
    tablaAlumnos.getColumnModel().getColumn(5).setPreferredWidth(0);


}//GEN-LAST:event_txtCriterioKeyReleased

private void cmbCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCampoActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_cmbCampoActionPerformed

private void cmbCampoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCampoItemStateChanged
    // TODO add your handling code here:
    objalumno = new Alumnos();
    objalumno.setNombre(txtCriterio.getText());
    texto = this.cmbCampo.getSelectedItem().toString();

    lista = ctrlalumno.getBuscarAlumnos(objalumno, texto);
    this.jLabel3.setText(String.valueOf(lista.size()));
    this.tablaAlumnos.setModel(ctrlalumno.getPersonal(lista));
    tablaAlumnos.getColumnModel().getColumn(0).setMaxWidth(0);
    tablaAlumnos.getColumnModel().getColumn(0).setMinWidth(0);
    tablaAlumnos.getColumnModel().getColumn(0).setPreferredWidth(0);

    tablaAlumnos.getColumnModel().getColumn(5).setMaxWidth(0);
    tablaAlumnos.getColumnModel().getColumn(5).setMinWidth(0);
    tablaAlumnos.getColumnModel().getColumn(5).setPreferredWidth(0);

}//GEN-LAST:event_cmbCampoItemStateChanged

private void tablaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnosMouseClicked
    // TODO add your handling code here:
    /* int filas=this.tablaAlumnos.rowAtPoint(evt.getPoint());
    if(filas>-1)
    {
    Alumnos objalumn=new Alumnos();
    int id=Integer.parseInt(String.valueOf(this.tablaAlumnos.getValueAt(filas , 0)));
    objalumn.setIdAlumno(id);
    objalumn=ctrlalumno.getPersonal(objalumn,this.lista );
    if(objalumn.getNombre()!=null)
    {
    try {
    frmInscripcion1 frmalumno=new frmInscripcion1(this,true);
    frmalumno.setAlumno(objalumn);
    frmalumno.setLocationRelativeTo(null);
    frmalumno.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
    frmalumno.setAlwaysOnTop(true);
    frmalumno.setVisible(true);
    } catch (SQLException ex) {
    Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
    Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    }*/
}//GEN-LAST:event_tablaAlumnosMouseClicked

private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    // TODO add your handling code here:
    int filas = this.tablaAlumnos.getSelectedRow();
    if (filas > -1) {
        Alumnos objalumn = new Alumnos();
        int id = Integer.parseInt(String.valueOf(this.tablaAlumnos.getValueAt(filas, 0)));
        objalumn.setIdAlumno(id);
        objalumn = ctrlalumno.getPersonal(objalumn, this.lista);
        Alumnos mialumno = objalumn;
        if (objalumn.getNombre() != null) {
            try {
                frmCrearKardex crearkardex = new frmCrearKardex(this, true);
                crearkardex.setAlumno(mialumno);
                crearkardex.setLocationRelativeTo(null);

                crearkardex.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    } else {
        JOptionPane.showMessageDialog(this, "Dese seleccionar un Alumno");
    }
}//GEN-LAST:event_btnAgregarActionPerformed

private void btnEditarKardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarKardexActionPerformed
    // TODO add your handling code here:
    int filas = this.tablaAlumnos.getSelectedRow();
    if (filas > -1) {
        try {
            Alumnos objalumn = new Alumnos();
            int id = Integer.parseInt(String.valueOf(this.tablaAlumnos.getValueAt(filas, 0)));
            objalumn.setIdAlumno(id);
            ctrlAlumnos ctrlal = new ctrlAlumnos();
            objalumn = ctrlal.getAlumno(objalumn);

            frmEditarKardex frmeditarkardex = new frmEditarKardex(this, true);
            // System.out.println("Id" +objalumn.getIdAlumno());
            frmeditarkardex.setAlumno(objalumn);
            //frmeditarkardex.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
            //frmeditarkardex.setAlwaysOnTop(true);
            frmeditarkardex.setLocationRelativeTo(null);
            frmeditarkardex.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(Level.SEVERE, null, ex);
        }

    } else {
        JOptionPane.showMessageDialog(this, "Dese seleccionar Un Alumno");
    }

}//GEN-LAST:event_btnEditarKardexActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    int filas = this.tablaAlumnos.getSelectedRow();
    if (filas > -1) {
        try {
            Alumnos objalumn = new Alumnos();
            int id = Integer.parseInt(String.valueOf(this.tablaAlumnos.getValueAt(filas, 0)));
            objalumn.setIdAlumno(id);
            objalumn = ctrlalumno.getAlumno(objalumn);
            Alumnos mialumno = objalumn;





            ctrlKardex ctrlka = new ctrlKardex();
            ArrayList<ReporteHistorialAcademico> r = ctrlka.getReporteHistorialAcademico(id);
            if (r != null) {
                if (r.size() > 0) {
                    JRDHistorialAcademicoAlumno reporte = new JRDHistorialAcademicoAlumno();
                    for (int i = 0; i < r.size(); i++) {

                        reporte.addRegistroReporte(r.get(i));

                    }
                    String ruta = System.getProperty("user.dir");
                    String archivo = "historial_academico.jrxml";//=ruta+"\\src\\Reportes\\formatoREDI.jrxml";

                    archivo = ruta + "\\src\\Reportes\\" + archivo;
                    Map pars = new HashMap();
                    pars.put("p_matricula", objalumn.getMatricula());
                    pars.put("p_nombre", objalumn.getNombre());
                    JasperDesign jasperDesign = JRXmlLoader.load(archivo); //Cargamos el reporte jrxml para generar el jasper
                    JasperReport jasper = JasperCompileManager.compileReport(jasperDesign); //Compilamos para generar el jasper
                    JasperPrint jasperprint = JasperFillManager.fillReport(jasper, pars, reporte);
                    if (jasperprint.getPages().size() > 0) //Vemos si el reporte tiene hojas (registros) sino no tiene caso abrir el visor
                    {
                        JasperViewer.viewReport(jasperprint, false);



                    } else {
                        JOptionPane.showMessageDialog(null, "NO HAY REGISTROS");
                    }

                }
            }


        } catch (JRException ex) {
            Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(Level.SEVERE, null, ex);
        }

    } else {
        JOptionPane.showMessageDialog(this, "Dese seleccionar una fila");
    }



}//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    dlgBuscarAlumnokardex dialog = new dlgBuscarAlumnokardex(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(dlgBuscarAlumnokardex.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditarKardex;
    private javax.swing.JComboBox cmbCampo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JTextField txtCriterio;
    // End of variables declaration//GEN-END:variables
}
