/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dlgMasOfertaAcademica.java
 *
 * Created on 02-jul-2012, 22:42:45
 */
package Formularios;

import Controladores.ModeloOfertaAsignaturas;
import Controladores.ctrlCicloEscolar;
import Controladores.ctrlInscripciones;
import Controladores.ctrlOfertaAcademica;
import Entidades.Alumnos;
import Entidades.CicloEscolar;
import Entidades.Inscripciones;
import Entidades.OfertaAcademica;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Last Develop
 */
public class dlgMasOfertaAcademica extends javax.swing.JDialog {
private Alumnos al=null;

    /** Creates new form dlgMasOfertaAcademica */
    public dlgMasOfertaAcademica(java.awt.Dialog parent, boolean modal,Alumnos al) {
        super(parent, modal);
        initComponents();
        this.al=al;
        this.getMasOfertaAcademica();
    }

    private dlgMasOfertaAcademica(JDialog jDialog, boolean b) {
        
    }
private void getMasOfertaAcademica()
{
        try {
            ctrlOfertaAcademica ctrloferta=new ctrlOfertaAcademica();
            ArrayList<OfertaAcademica> listaoferta=ctrloferta.getMasOfertaAcademica(al.getIdAlumno());
            for(int i=0;i<listaoferta.size();i++)
            {
                OfertaAcademica e=listaoferta.get(i);
                e.setSeleccionado(false);
             listaoferta.set(i, e);
            }
            ModeloOfertaAsignaturas modelo=ctrloferta.getOfertaInscripcion(listaoferta);
            this.jTable1.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(dlgMasOfertaAcademica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dlgMasOfertaAcademica.class.getName()).log(Level.SEVERE, null, ex);
        }
 
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Más Oferta ACadémica");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Oferta Académica del Ciclo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 // TODO add your handling code here:
    if(JOptionPane.showConfirmDialog(this,"¿Desea Guardar los Cambios?")==JOptionPane.YES_OPTION)
    {
     ctrlInscripciones ctrlinscripcion =new ctrlInscripciones();
        ArrayList<Inscripciones>  listaAjuste=this.getInscripcionAjuste();
        if(listaAjuste.size()>0)
        {
                try {
                    boolean band=ctrlinscripcion.setAjusteCargaAcademica(listaAjuste);
                    if(band)
                    {
                     JOptionPane.showMessageDialog(this, "Los Cambios Se Guardaron con Éxito","Aviso",JOptionPane.INFORMATION_MESSAGE);
                     this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Los Cambios No se Guardaron debido a un ERROR","Aviso",JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(dlgMasOfertaAcademica.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(dlgMasOfertaAcademica.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
    }
    
        
}//GEN-LAST:event_jButton1ActionPerformed

private ArrayList<Inscripciones> getInscripcionAjuste()
{ 
     ArrayList<Inscripciones> listaAjuste=new ArrayList<Inscripciones>();
        try {
           
            ModeloOfertaAsignaturas modelo=(ModeloOfertaAsignaturas) this.jTable1.getModel();
            ArrayList<OfertaAcademica> lista= modelo.getListaOfertaAcademica();
            ctrlCicloEscolar ctrlciclo=new ctrlCicloEscolar();
            CicloEscolar activo=ctrlciclo.getCicloActivo();
            
            
                      for(int i=0;i<lista.size();i++)
                      {
                          if(lista.get(i).isSeleccionado())
                          {
                              Inscripciones ajuste=new Inscripciones();
                              ajuste.setId_inscripcion(0);
                              ajuste.setId_alumno(al.getIdAlumno());
                              ajuste.setId_oferta_academica(lista.get(i).getIdOfertaAcademica());
                              ajuste.setId_ciclo(activo.getIdCiclo());
                              ajuste.setRecursamiento("N");
                              ajuste.setModulo(lista.get(i).getAsignatura().getModulo());
                              ajuste.setId_asignatura(lista.get(i).getIdAsignatura());
                              listaAjuste.add(ajuste);
                              
                              
                          }
                      }
                      
        } catch (SQLException ex) {
            Logger.getLogger(dlgMasOfertaAcademica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dlgMasOfertaAcademica.class.getName()).log(Level.SEVERE, null, ex);
        }
        return listaAjuste;
}

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
 // TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgMasOfertaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgMasOfertaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgMasOfertaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgMasOfertaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                dlgMasOfertaAcademica dialog = new dlgMasOfertaAcademica(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
