/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmCiclos.java
 *
 * Created on 5/02/2012, 12:06:22 PM
 */
package Formularios;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import Controladores.ctrlCicloEscolar;
import Entidades.CicloEscolar;

/**
 *
 * @author leonel
 */
public class frmCiclos extends javax.swing.JDialog {
   CicloEscolar ce = new CicloEscolar(); 
   ctrlCicloEscolar ciclo = new ctrlCicloEscolar();
   ArrayList<CicloEscolar> lstCiclos = new ArrayList<CicloEscolar>();
   DefaultTableModel modelo;  
   int fila = -1;
   SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
   Date fechaInicial = new Date();
   Date fechaFinal = new Date();
   Date fechaParcial1 = new Date();   
   Date fechaParcial2 = new Date();   
   Date fechaParcial3 = new Date();      

    /** Creates new form frmCiclos */
    public frmCiclos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.dpFechaInicio.setFormats("dd-MM-yyyy");
        this.dpFechaFin.setFormats("dd-MM-yyyy");    
        this.dpFechaParcial1.setFormats("dd-MM-yyyy");
        this.dpFechaParcial2.setFormats("dd-MM-yyyy");
        this.dpFechaParcial3.setFormats("dd-MM-yyyy");        
        //this.lblActivo.setVisible(false);
        try {
            updateTabla();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmCiclos.class.getName()).log(Level.SEVERE, null, ex);
        }
        limpiar();     
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPeriodo = new javax.swing.JTextField();
        dpFechaInicio = new org.jdesktop.swingx.JXDatePicker();
        dpFechaFin = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        lblIdCiclo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        dpFechaParcial1 = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        dpFechaParcial2 = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        dpFechaParcial3 = new org.jdesktop.swingx.JXDatePicker();
        jLabel9 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Semestre", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel2.setText("Periodo:");

        jLabel3.setText("Inicio:");

        jLabel4.setText("Fin:");

        jLabel5.setText("Clave:");

        lblIdCiclo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Programación de Entrega de Exámenes Parciales", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP));

        jLabel6.setText("Parcial1:");

        jLabel7.setText("Parcial2:");

        jLabel8.setText("Parcial3:");

        jLabel9.setText("Tipo:");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "Intersemestral" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dpFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(dpFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblIdCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpFechaParcial1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpFechaParcial2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dpFechaParcial3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dpFechaFin, dpFechaInicio});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(lblIdCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(dpFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dpFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dpFechaParcial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(dpFechaParcial2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(dpFechaParcial3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel1.setText("Listado de Semestres");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
// TODO add your handling code here:
        fila = tabla.rowAtPoint(evt.getPoint());                 
           if (fila > -1){                                      
      try {
        lblIdCiclo.setText(String.valueOf(tabla.getValueAt(fila, 0)));           
        txtPeriodo.setText(String.valueOf(tabla.getValueAt(fila, 1))); 
        int i = Short.parseShort(String.valueOf(tabla.getValueAt(fila, 2)));
        cmbTipo.setSelectedIndex((short)(i-1));
        
        String f[];
        f = tabla.getValueAt(fila, 3).toString().split("-");
        fechaInicial = formato.parse(f[2]+"-"+f[1]+"-"+f[0]);
        f = tabla.getValueAt(fila, 4).toString().split("-");
        fechaFinal = formato.parse(f[2]+"-"+f[1]+"-"+f[0]);
        dpFechaInicio.setDate(fechaInicial);
        dpFechaFin.setDate(fechaFinal);
        
        f = tabla.getValueAt(fila, 6).toString().split("-");
        fechaParcial1 = formato.parse(f[2]+"-"+f[1]+"-"+f[0]);
        
        f = tabla.getValueAt(fila, 7).toString().split("-");
        fechaParcial2 = formato.parse(f[2]+"-"+f[1]+"-"+f[0]);

        f = tabla.getValueAt(fila, 8).toString().split("-");
        fechaParcial3 = formato.parse(f[2]+"-"+f[1]+"-"+f[0]);
        
        dpFechaParcial1.setDate(fechaParcial1);        
        dpFechaParcial2.setDate(fechaParcial2);        
        dpFechaParcial3.setDate(fechaParcial3);       
        
      } catch (ParseException ex) {
        Logger.getLogger(frmCiclos.class.getName()).log(Level.SEVERE, null, ex);
      }
         }
}//GEN-LAST:event_tablaMouseClicked

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
// TODO add your handling code here:
  this.limpiar();
}//GEN-LAST:event_btnNuevoActionPerformed

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// TODO add your handling code here:  
    guardar();
}//GEN-LAST:event_btnGuardarActionPerformed

private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
// TODO add your handling code here:
  eliminar();
}//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCiclos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCiclos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCiclos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCiclos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmCiclos dialog = new frmCiclos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

  private  void guardar(){
    try {
    if (validar() ) {
    
      if (JOptionPane.showConfirmDialog(this, "¿Deseas guardar los cambios?") == JOptionPane.YES_OPTION) {

        if ("".equals(lblIdCiclo.getText())) {
          ce.setIdCiclo(0);      
          ce.setActivo(null); //Todos los ciclos cuando se crean son nulos          
        }else{
          ce.setIdCiclo(Integer.parseInt(lblIdCiclo.getText()));                      
        }

        ce.setPeriodo(txtPeriodo.getText());
        ce.setTipo((short)(cmbTipo.getSelectedIndex()+ 1));

        String fecha_inicial = String.valueOf(dpFechaInicio.getEditor().getText());
        String fecha_final = String.valueOf(dpFechaFin.getEditor().getText());     
        String fecha_parcial1 = String.valueOf(dpFechaParcial1.getEditor().getText());
        String fecha_parcial2 = String.valueOf(dpFechaParcial2.getEditor().getText());        
        String fecha_parcial3 = String.valueOf(dpFechaParcial3.getEditor().getText());                
        ce.setFechaInicial(fecha_inicial); //se debe enviar como año/mes/dia
        ce.setFechaFinal(fecha_final); //se debe enviar como año/mes/dia
        //Estos datos están pendientes por modificar

        ce.setFechaParcial1(fecha_parcial1); //se debe enviar como año/mes/dia
        ce.setFechaParcial2(fecha_parcial2); //se debe enviar como año/mes/dia
        ce.setFechaParcial3(fecha_parcial3); //se debe enviar como año/mes/dia        
        
        int result = ciclo.guardarCiclo(ce);

            if (result > 0) {
             updateTabla();
             limpiar();
              JOptionPane.showMessageDialog(this, "Los cambios fueron realizados con éxito");             
            }else{
              JOptionPane.showMessageDialog(this, "El ciclo escolar no pudo agregarse debido a un problema");                    
            }// fin de if (result > 0)     
          } //fin de ¿Guardar los cambios?
        } //fin de validar
    }catch (Exception e){
     JOptionPane.showMessageDialog(this, "error" + e.getMessage());                
    }
  }
  
  private void eliminar(){
    try {    
      if (!"".equals(lblIdCiclo.getText())) {
      if (JOptionPane.showConfirmDialog(this, "¿Deseas eliminar esta ciclo escolar?") == JOptionPane.YES_OPTION) {
        int id_ciclo = Integer.parseInt(lblIdCiclo.getText());
        int result = ciclo.deleteCiclo(id_ciclo);
        if (result > 0) {
          updateTabla();
          limpiar();
          JOptionPane.showMessageDialog(this, "El ciclo escolar fue eliminado con éxito");             
        }else{
          JOptionPane.showMessageDialog(this, "El ciclo escolar no pudo eliminarse debido a un problema");                    
        }
      }
      }else{
          JOptionPane.showMessageDialog(this, "Selecciona un ciclo escolar");                     
      }
    }catch (Exception e) {
      JOptionPane.showMessageDialog(this, e.getMessage());                          
    }
    
  }
  
  private void updateTabla() throws ClassNotFoundException{             

        try {

          modelo =  new DefaultTableModel();
          modelo = ciclo.getCiclos(ciclo.getCiclos(0));
          tabla.setModel(modelo);
          tabla.getColumnModel().getColumn(0).setMaxWidth(0);
          tabla.getColumnModel().getColumn(0).setMinWidth(0);
          tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
        }catch (SQLException e){
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());                    
        }
    }
  
  private void limpiar(){
          lblIdCiclo.setText("");
          txtPeriodo.setText("");
          //dpFechaInicio.setDate(Date.valueOf(""));
          //dpFechaFin.setDate(Date.valueOf(""));
          Date hoy = new Date();
          this.dpFechaInicio.setDate(hoy);
          this.dpFechaFin.setDate(hoy);    
          this.dpFechaParcial1.setDate(hoy);          
          this.dpFechaParcial2.setDate(hoy);          
          this.dpFechaParcial3.setDate(hoy);                    
          /*
          ce.setIdCiclo(null);
          ce.setPeriodo(null);    
          ce.setFechaInicial(null);
          ce.setFechaInicial(null);
          ce.setEstado(null);
          ce.setActivo(null);
           * 
           */
  }
   
  
  private boolean validar(){
    boolean result=false;

    if ("".equals(txtPeriodo.getText())){
      JOptionPane.showMessageDialog(this, "Escribe la descripción del periodo");                    
      result = false;
    }else{ 
      result = true;
    } 
    
    return result;
    
  }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbTipo;
    private org.jdesktop.swingx.JXDatePicker dpFechaFin;
    private org.jdesktop.swingx.JXDatePicker dpFechaInicio;
    private org.jdesktop.swingx.JXDatePicker dpFechaParcial1;
    private org.jdesktop.swingx.JXDatePicker dpFechaParcial2;
    private org.jdesktop.swingx.JXDatePicker dpFechaParcial3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIdCiclo;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtPeriodo;
    // End of variables declaration//GEN-END:variables
}
