/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmGrupos.java
 *
 * Created on 5/02/2012, 01:18:33 PM
 */
package Formularios;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
import Controladores.ctrlCarreras;
import Controladores.ctrlGeneraciones;
import Controladores.ctrlGrupos;
import Controladores.ctrlPlanes;
import Controladores.ctrlAreas;
import Controladores.ctrlCicloEscolar;
import Entidades.Carreras;
import Entidades.Planes;
import Entidades.Generaciones;
import Entidades.Grupos;
import Entidades.Areas;
import Entidades.CicloEscolar;

/**
 *
 * @author leonel
 */
public class frmGrupos extends javax.swing.JDialog {
   Grupos g = new Grupos(); 
   ctrlGrupos grupo = new ctrlGrupos();
   CicloEscolar c = new CicloEscolar();
   ctrlCicloEscolar ciclo = new ctrlCicloEscolar();
   ArrayList<Grupos> lstGrupos = new ArrayList<Grupos>();
   //DefaultTableModel modelo;  
  int id_generacion = 0;
  int id_carrera = 0;
  int id_plan = 0;
  int id_grupo = 0;
  int id_area = 0;

    /** Creates new form frmGrupos */
    public frmGrupos(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        updateComboGeneraciones();        
        updateComboCarreras();        
        updateComboPlanes();        
        updateComboAreas();
        this.btnPlanEstudios.setVisible(false);
    }
    
    public frmGrupos(java.awt.Dialog parent, boolean modal, Grupos varGrupo) {
        super(parent, modal);
        initComponents();
        updateComboGeneraciones();
        updateComboCarreras();
        updateComboPlanes();
        updateComboAreas();
        g = varGrupo;
        cargaDatos();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        cmbModalidad = new javax.swing.JComboBox();
        txtClave = new javax.swing.JTextField();
        cmbGeneracion = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox();
        cmbPlan = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbSemestre = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTurno = new javax.swing.JComboBox();
        cmbArea = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPlanEstudios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel1.setText("Alta - Edición del Grupo");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Grupo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel5.setText("Grupo:");

        jLabel7.setText("Modalidad:");

        jLabel8.setText("Clave:");

        txtGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrupoActionPerformed(evt);
            }
        });

        cmbModalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Educación Presencial", "Educación Mixta" }));

        cmbGeneracion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGeneracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGeneracionActionPerformed(evt);
            }
        });

        jLabel9.setText("Generación:");

        jLabel11.setText("Valor Opcional");

        cmbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarreraActionPerformed(evt);
            }
        });

        cmbPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlanActionPerformed(evt);
            }
        });

        jLabel13.setText("Plan:");

        jLabel3.setText("Carrera:");

        cmbSemestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        cmbSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSemestreActionPerformed(evt);
            }
        });

        jLabel12.setText("Semestre");

        jLabel6.setText("Turno:");

        cmbTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matutino", "Vespertino", "Nocturno" }));
        cmbTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTurnoActionPerformed(evt);
            }
        });

        cmbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaActionPerformed(evt);
            }
        });

        jLabel14.setText("Area Propedéutica:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCarrera, 0, 360, Short.MAX_VALUE)
                            .addComponent(cmbModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel11))
                                .addGap(72, 72, 72))
                            .addComponent(cmbGeneracion, 0, 360, Short.MAX_VALUE)
                            .addComponent(cmbPlan, 0, 360, Short.MAX_VALUE)
                            .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtClave)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel5)
                    .addComponent(cmbSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnPlanEstudios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver_kardex.png"))); // NOI18N
        btnPlanEstudios.setText("Plan de Estudios");
        btnPlanEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanEstudiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPlanEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar)
                    .addComponent(btnPlanEstudios))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrupoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtGrupoActionPerformed

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// TODO add your handling code here:
  this.guardar();
}//GEN-LAST:event_btnGuardarActionPerformed

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// TODO add your handling code here:
  this.setVisible(false);
  this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

    private void cmbGeneracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGeneracionActionPerformed

   }//GEN-LAST:event_cmbGeneracionActionPerformed

    private void cmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarreraActionPerformed
        // TODO add your handling code here:
        
        if (cmbSemestre.getSelectedIndex()==0) {
            cmbCarrera.setSelectedIndex(0);
        }else{
            Carreras ca = (Carreras) cmbCarrera.getSelectedItem();
            if (ca != null) {
              id_carrera = ca.getIdCarrera();
            }                    
        }
    }//GEN-LAST:event_cmbCarreraActionPerformed

    private void cmbPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlanActionPerformed
        // TODO add your handling code here:
        Planes p = (Planes) cmbPlan.getSelectedItem();
        if (p != null) {
          id_plan = p.getIdPlan();
        }            
        
    }//GEN-LAST:event_cmbPlanActionPerformed

private void cmbSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSemestreActionPerformed
        // TODO add your handling code here:
    //Si es Primer semestre
    if (cmbSemestre.getSelectedIndex()<=3){
        cmbArea.setSelectedIndex(0);
        if (cmbSemestre.getSelectedIndex()==0) {
            cmbCarrera.setSelectedIndex(0);
        }
    }
    
    
    
}//GEN-LAST:event_cmbSemestreActionPerformed

private void cmbTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTurnoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cmbTurnoActionPerformed

private void cmbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaActionPerformed
// TODO add your handling code here:
        if (cmbSemestre.getSelectedIndex()<=3) {
            cmbArea.setSelectedIndex(0);
        }else{
            Areas ar = (Areas) cmbArea.getSelectedItem();
            if (ar != null) {
              id_area = ar.getIdArea();
            }                    
        }
    
}//GEN-LAST:event_cmbAreaActionPerformed

private void btnPlanEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanEstudiosActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnPlanEstudiosActionPerformed


  private void cargaDatos(){
      
      id_grupo = g.getIdGrupo(); //Permite modificar los datos
      
      //Cargamos El ciclo escolar en el combo
      Generaciones ge = new Generaciones();
      ge.setIdGeneracion(g.getIdGeneracion());
      this.cmbGeneracion.setSelectedItem(ge);
      
      //Cargamos el plan en el combo
      Planes plan = new Planes();
      plan.setIdPlan(g.getIdPlan());
      this.cmbPlan.setSelectedItem(plan);
      
      
      this.txtClave.setText(g.getClave());
      this.txtGrupo.setText(g.getGrupo());
      this.cmbSemestre.setSelectedIndex(g.getSemestre()-1);      
      
      //Cargamos la carrera en el combo
      Carreras ca = new Carreras();
      ca.setIdCarrera(g.getIdCarrera());
      this.cmbCarrera.setSelectedItem(ca);
      
      //Cargamos la carrera en el combo
      Areas ar = new Areas();
      ar.setIdArea(g.getIdArea());
      this.cmbArea.setSelectedItem(ar);
      
      
      if ("Matutino".equals(g.getTurno())) {
          this.cmbTurno.setSelectedIndex(0);
      }else if ("Vespertino".equals(g.getTurno())) {
          this.cmbTurno.setSelectedIndex(1);          
      }else if ("Nocturno".equals(g.getTurno())) {
          this.cmbTurno.setSelectedIndex(2);          
      }
      
      this.cmbModalidad.setSelectedItem(g.getModalidad());

  }

  private  void guardar(){
    try {
    if (validar()==true) {
    
      if (JOptionPane.showConfirmDialog(this, "¿Deseas guardar los cambios?") == JOptionPane.YES_OPTION) {

        if (id_grupo == 0) {
          g.setIdGrupo(0);      
        }else{
          g.setIdGrupo(id_grupo);
        }
        
        c = ciclo.getCicloActivo();
        
        g.setIdCiclo(c.getIdCiclo());
        
        g.setSemestre(Integer.parseInt(cmbSemestre.getSelectedItem().toString()));
        g.setGrupo(txtGrupo.getText());
        g.setTurno(cmbTurno.getSelectedItem().toString());
        g.setModalidad(cmbModalidad.getSelectedItem().toString());

        
        if (id_carrera == 0) {
          g.setIdCarrera(0);      
        }else{
          g.setIdCarrera(id_carrera);
        }
        
        g.setIdPlan(id_plan);
        
        if (id_area == 0) {
          g.setIdArea(0);      
        }else{
          g.setIdArea(id_area);
        }
        
        g.setIdGeneracion(id_generacion);
        g.setClave(txtClave.getText());
        int result = grupo.setGrupo(g);
            if (result > 0) {
              JOptionPane.showMessageDialog(this, "Los cambios fueron realizados con éxito");             
              this.setVisible(false);
            }else{
              JOptionPane.showMessageDialog(this, "El ciclo escolar no pudo agregarse debido a un problema");                    
            }// fin de if (result > 0)     
          } //fin de ¿Guardar los cambios?
        } //fin de validar
    }catch (Exception e){
     JOptionPane.showMessageDialog(this, "error" + e.getMessage());                
    }
  }

    private void updateComboGeneraciones() {
         ctrlGeneraciones generacion = new ctrlGeneraciones();
         ArrayList<Generaciones> lstGeneraciones = new ArrayList<Generaciones>();
         try {
          lstGeneraciones = generacion.getGeneraciones(0);
          DefaultComboBoxModel modeloCombo;         
          modeloCombo =  new DefaultComboBoxModel();
          modeloCombo.removeAllElements();
          modeloCombo = generacion.getComboGeneraciones(lstGeneraciones);
          cmbGeneracion.setModel(modeloCombo);          
          
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());                               
         }
  }


  private void updateComboCarreras() {
         ctrlCarreras carrera = new ctrlCarreras();
         ArrayList<Carreras> lstCarreras = new ArrayList<Carreras>();

         try {
          lstCarreras = carrera.getCarreras(0);
          DefaultComboBoxModel modeloCombo;         
          modeloCombo =  new DefaultComboBoxModel();
          modeloCombo.removeAllElements();
          modeloCombo = carrera.getComboCarreras(lstCarreras);
          cmbCarrera.setModel(modeloCombo);                    
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());                               
         }
  }
  
  private void updateComboPlanes() {
         ctrlPlanes plan = new ctrlPlanes();
         ArrayList<Planes> lstPlanes = new ArrayList<Planes>();
         try {
            lstPlanes = plan.getPlanes(0);
            DefaultComboBoxModel modeloCombo;         
            modeloCombo =  new DefaultComboBoxModel();
            modeloCombo.removeAllElements();
            modeloCombo = plan.getComboPlanes(lstPlanes);
            cmbPlan.setModel(modeloCombo);                    
           
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());                               
         }
  }
  
      private void updateComboAreas() {
         ctrlAreas area = new ctrlAreas();
         ArrayList<Areas> lstAreas = new ArrayList<Areas>();
         try {
          lstAreas = area.getAreas(0);
          DefaultComboBoxModel modeloCombo;         
          modeloCombo =  new DefaultComboBoxModel();
          modeloCombo.removeAllElements();
          modeloCombo = area.getComboAreas(lstAreas);
          cmbArea.setModel(modeloCombo);                    
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());                               
         }
  }

  
  private boolean validar() throws SQLException, ClassNotFoundException{
    boolean result=false;

    Generaciones ge = (Generaciones) cmbGeneracion.getSelectedItem();
    if (ge != null) {
      id_generacion = ge.getIdGeneracion();
    }                
       
    Planes pa = (Planes) cmbPlan.getSelectedItem();
    if (pa != null) {
      id_plan = pa.getIdPlan();
    }            
    
    Carreras ca = (Carreras) cmbCarrera.getSelectedItem();
    if (ca != null) {
      id_carrera = ca.getIdCarrera();
    }            
    
    int sm = cmbSemestre.getSelectedIndex()+1;
    String gr = txtGrupo.getText();
    
    Areas ar = (Areas) cmbArea.getSelectedItem();
    if (ar != null) {
      id_area = ar.getIdArea();
    }            
    
    g.setIdGeneracion(id_generacion);
    g.setIdPlan(id_plan);
    g.setIdCarrera(id_carrera);
    g.setSemestre(sm);
    g.setGrupo(gr);
    g.setIdArea(id_area);
    
    if (grupo.getGrupoValidar(g)>0){
      JOptionPane.showMessageDialog(this, "El grupo que intentas agregar ya existe");                                       
    }else if (id_generacion == 0) {
      JOptionPane.showMessageDialog(this, "Selecciona una generación");                               
    }else if (id_plan == 0) {
      JOptionPane.showMessageDialog(this, "Selecciona un plan");                                     
    } else if ("".equals(txtGrupo.getText())) {
      JOptionPane.showMessageDialog(this, "Escribe el grupo");                               
    } else {
      result = true;
    }
    System.out.println(result);
    return result;
    
  }

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmGrupos dialog = new frmGrupos(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnPlanEstudios;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbArea;
    private javax.swing.JComboBox cmbCarrera;
    private javax.swing.JComboBox cmbGeneracion;
    private javax.swing.JComboBox cmbModalidad;
    private javax.swing.JComboBox cmbPlan;
    private javax.swing.JComboBox cmbSemestre;
    private javax.swing.JComboBox cmbTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtGrupo;
    // End of variables declaration//GEN-END:variables
}