/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmListaGrupos.java
 *
 * Crea ted on 5/02/2012, 01:07:28 PM
 */
package Formularios;

import Controladores.MyTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import Controladores.ctrlCarreras;
import Controladores.ctrlGeneraciones;
import Controladores.ctrlGrupos;
import Controladores.ctrlPlanes;
import Entidades.Carreras;
import Entidades.Grupos;
import Entidades.Generaciones;
import Entidades.Planes;

/**
 *
 * @author leonel
 */
public class frmListaGrupos extends javax.swing.JDialog {

    Grupos g = new Grupos();
    ctrlGrupos grupo = new ctrlGrupos();
    ArrayList<Grupos> lstGrupos = new ArrayList<Grupos>();
    DefaultTableModel modelo;
    int fila = -1;
    int id_carrera = 0;
    int id_plan = 0;
    int id_generacion = 0;
    int opcion = 0;

    /** Creates new form frmListaGrupos */
    public frmListaGrupos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        updateComboGeneraciones();
        updateComboCarreras();
        updateComboPlanes();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbGeneracion = new javax.swing.JComboBox();
        cmbCarrera = new javax.swing.JComboBox();
        cmbPlan = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnOfertaAcademica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Búsqueda por", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel2.setText("Generación:");

        jLabel3.setText("Carrera:");

        cmbGeneracion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGeneracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGeneracionActionPerformed(evt);
            }
        });

        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarreraActionPerformed(evt);
            }
        });

        cmbPlan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona un plan" }));
        cmbPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlanActionPerformed(evt);
            }
        });

        jLabel4.setText("Plan:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbPlan, 0, 241, Short.MAX_VALUE)
                    .addComponent(cmbGeneracion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCarrera, 0, 241, Short.MAX_VALUE))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel1.setText("Listado de Grupos");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");

        btnOfertaAcademica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver_kardex.png"))); // NOI18N
        btnOfertaAcademica.setText("Plan de Estudios");
        btnOfertaAcademica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOfertaAcademicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOfertaAcademica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnOfertaAcademica, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar)
                    .addComponent(btnNuevo)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmbGeneracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGeneracionActionPerformed
    try {
        // TODO add your handling code here:
        filtrar();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(frmListaGrupos.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_cmbGeneracionActionPerformed

private void cmbCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarreraActionPerformed
    try {

//        Carreras ca = (Carreras) cmbCarrera.getSelectedItem();
//        if (ca != null) {
//          id_carrera = ca.getIdCarrera();
//          updateComboPlanes();
//        }            
        filtrar();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(frmListaGrupos.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_cmbCarreraActionPerformed

private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
// TODO add your handling code here:

    if (evt.getClickCount() == 2) {
        modificar();
    }
}//GEN-LAST:event_tablaMouseClicked

private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    try {
        // TODO add your handling code here:
        //frmGruposM fg = new frmGruposM(this,true); 
        //fg.setLocationRelativeTo(this);  
        //fg.setVisible(true);
        frmGrupos frmgrupo = new frmGrupos(this, true);
        frmgrupo.setLocationRelativeTo(this);
        frmgrupo.setVisible(true);
        this.updateTabla();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(frmListaGrupos.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_btnNuevoActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    try {
        // TODO add your handling code here:
        this.updateTabla();
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(frmListaGrupos.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_formWindowOpened

    private void cmbPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlanActionPerformed
        try {
            filtrar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmListaGrupos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmbPlanActionPerformed

private void btnOfertaAcademicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOfertaAcademicaActionPerformed
// TODO add your handling code here:
    ofertaAcademica();
}//GEN-LAST:event_btnOfertaAcademicaActionPerformed

private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
// TODO add your handling code here:
    modificar();
}//GEN-LAST:event_btnModificarActionPerformed

    private void updateComboGeneraciones() {
        ctrlGeneraciones generacion = new ctrlGeneraciones();
        ArrayList<Generaciones> lstGeneraciones = new ArrayList<Generaciones>();
        try {
            lstGeneraciones = generacion.getGeneraciones(0);
            DefaultComboBoxModel modeloCombo;
            modeloCombo = new DefaultComboBoxModel();
            modeloCombo.removeAllElements();
            modeloCombo = generacion.getComboGeneraciones(lstGeneraciones);
            cmbGeneracion.setModel(modeloCombo);
            //c.setIdCarrera(id_carrera); //Establecemos el id de la carrera
            //cmbCarrera.setSelectedItem(c);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());
        }
    }

    private void updateTabla() throws ClassNotFoundException {

        try {

            modelo = grupo.getGrupos(grupo.getGrupos(0, id_generacion, id_carrera, id_plan, opcion));
            tabla.setModel(modelo);

            tabla.getColumnModel().getColumn(0).setMaxWidth(0);
            tabla.getColumnModel().getColumn(0).setMinWidth(0);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(0);

            tabla.getColumnModel().getColumn(1).setMaxWidth(70);
            tabla.getColumnModel().getColumn(1).setMinWidth(70);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(70);

            tabla.getColumnModel().getColumn(2).setMaxWidth(70);
            tabla.getColumnModel().getColumn(2).setMinWidth(70);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(70);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());
        }
    }

    private void updateComboCarreras() {
        ctrlCarreras carrera = new ctrlCarreras();
        ArrayList<Carreras> lstCarreras = new ArrayList<Carreras>();
        try {
            lstCarreras = carrera.getCarreras(0);
            DefaultComboBoxModel modeloCombo;
            modeloCombo = new DefaultComboBoxModel();
            modeloCombo.removeAllElements();
            modeloCombo = carrera.getComboCarreras(lstCarreras);
            cmbCarrera.setModel(modeloCombo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());
        }
    }

    private void updateComboPlanes() {
        ctrlPlanes plan = new ctrlPlanes();
        ArrayList<Planes> lstPlanes = new ArrayList<Planes>();
        try {
            lstPlanes = plan.getPlanes(0);
            DefaultComboBoxModel modeloCombo;
            modeloCombo = new DefaultComboBoxModel();
            modeloCombo.removeAllElements();
            modeloCombo = plan.getComboPlanes(lstPlanes);
            cmbPlan.setModel(modeloCombo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());
        }
    }

    private void filtrar() throws ClassNotFoundException {
        
        Generaciones ge = (Generaciones) cmbGeneracion.getSelectedItem();
        if (ge != null) {
            id_generacion = ge.getIdGeneracion();
        }
        Carreras ca = (Carreras) cmbCarrera.getSelectedItem();
        if (ca != null) {
            id_carrera = ca.getIdCarrera();


        }
        
            Planes pa = (Planes) cmbPlan.getSelectedItem();
            if (pa != null) {
                id_plan = pa.getIdPlan();
            }
        

        if (id_generacion == 0 && id_carrera == 0 && id_plan == 0) {
            opcion = 0; //Todos los grupos            
        } else if (id_generacion != 0 && id_carrera == 0 && id_plan == 0) {
            opcion = 1; //Los grupos de una generacion
        } else if (id_generacion != 0 && id_carrera != 0 && id_plan == 0) {
            opcion = 2; //Los grupos de una generacion y carrera            
        } else if (id_generacion != 0 && id_carrera != 0 && id_plan != 0) {
            opcion = 3; //Los grupos de una generacion, carrera y plan
        } else if (id_generacion == 0 && id_carrera != 0 && id_plan == 0) {
            opcion = 4; //Los grupos de una generacion, carrera y plan
        } else if (id_generacion == 0 && id_carrera != 0 && id_plan != 0) {
            opcion = 5; //Los grupos de una generacion, carrera y plan
        } else if (id_generacion == 0 && id_carrera == 0 && id_plan != 0) {
            opcion = 6; //Los grupos de una generacion, carrera y plan
        } else if (id_generacion != 0 && id_carrera == 0 && id_plan != 0) {
            opcion = 7; //Los grupos de una generacion, carrera y plan
        }


        updateTabla();
    }

    private void ofertaAcademica() {
        fila = tabla.getSelectedRow();
        int idGrupo;
        if (fila > -1) {
            try {
                idGrupo = Integer.parseInt(String.valueOf(tabla.getValueAt(fila, 0)));
                //Obteniendo el objeto grupo con el ID seleccionado
                lstGrupos = grupo.getGrupos(idGrupo, 0, 0, 0, 8);
                g = lstGrupos.get(0);

                frmOfertaAcademica frmoferta = new frmOfertaAcademica(this, true, g);
                frmoferta.setLocationRelativeTo(this);
                frmoferta.setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(frmListaGrupos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmListaGrupos.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }
    
    private void modificar(){
        int idGrupo;
        fila = tabla.getSelectedRow();
        if (fila > -1) {
                try {
                    idGrupo = Integer.parseInt(String.valueOf(tabla.getValueAt(fila, 0)));
                    //Obteniendo el objeto grupo con el ID seleccionado
                    lstGrupos = grupo.getGrupos(idGrupo, 0, 0, 0, 8);
                    g = lstGrupos.get(0);


                    frmGrupos frmgrupo = new frmGrupos(this, true, g);
                    frmgrupo.setLocationRelativeTo(this);
                    frmgrupo.setVisible(true);

                    this.updateTabla();
                } catch (SQLException ex) {
                    Logger.getLogger(frmListaGrupos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(frmListaGrupos.class.getName()).log(Level.SEVERE, null, ex);
                }

        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListaGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListaGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListaGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListaGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmListaGrupos dialog = new frmListaGrupos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnOfertaAcademica;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbCarrera;
    private javax.swing.JComboBox cmbGeneracion;
    private javax.swing.JComboBox cmbPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
