/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmGrupos.java
 *
 * Created on 5/02/2012, 01:18:33 PM
 */
package Formularios;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
import Controladores.*;
import Entidades.*;

/**
 *
 * @author leonel
 */
public class frmOfertaAcademica extends javax.swing.JDialog {
   OfertaAcademica oa = new OfertaAcademica();
   ctrlOfertaAcademica oferta = new ctrlOfertaAcademica();
   Grupos g = new Grupos(); 
   ctrlGrupos grupo = new ctrlGrupos();
   ArrayList<Grupos> lstGrupos = new ArrayList<Grupos>();
   CicloEscolar ce= new CicloEscolar();
   ctrlCicloEscolar cicloEscolar = new ctrlCicloEscolar();
   ArrayList<CicloEscolar> lstCicloEscolar = new ArrayList<CicloEscolar>();
   DefaultListModel m = new DefaultListModel();   
   ArrayList<Asignaturas> listaA = new ArrayList<Asignaturas>();
   
   
   //DefaultTableModel modelo;  
  int id_asignatura = 0;
  int id_generacion = 0;
  int id_carrera = 0;
  int id_plan = 0;
  int id_grupo = 0;
  int id_ciclo = 0;
  String ciclo = "";
  int id_grupo_ciclo = 0;
  int semestre;
  
    /** Creates new form frmGrupos */
    public frmOfertaAcademica(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);

            initComponents();
                                   
            //lstCicloEscolar = cicloEscolar.getCicloActivo();                   
            ce = lstCicloEscolar.get(0);            
            this.lblCicloEscolar.setText(ce.getPeriodo());
            id_ciclo = ce.getIdCiclo();
            

            
            
            updateComboGrupos();
    }
    
    public frmOfertaAcademica(java.awt.Dialog parent, boolean modal, Grupos varGrupo) {
        super(parent, modal);
        initComponents();
        updateComboGrupos();
        g = varGrupo;
        cargaDatos();
        updateListAsignaturas();
        updateListOfertaAsignaturas();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblCicloEscolar = new javax.swing.JLabel();
        lblGeneracion = new javax.swing.JLabel();
        lblSemestre = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblArea = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAsignaturas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstOfertaAsignaturas = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel1.setText("Oferta Académica");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Grupo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel5.setText("Generación:");

        jLabel9.setText("Ciclo Escolar:");

        jLabel6.setText("Semestre:");

        lblCicloEscolar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblGeneracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSemestre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblGrupo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Grupo:");

        jLabel8.setText("Carrera:");

        lblCarrera.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setText("Area Propedéutica:");

        lblArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblArea, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                            .addComponent(lblGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCicloEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(lblGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE))
                            .addComponent(lblCarrera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCicloEscolar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lblSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(lblGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 491, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 95, -1));

        jLabel2.setText("Asignaturas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        lstAsignaturas.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstAsignaturas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 196, 237));

        jScrollPane2.setViewportView(lstOfertaAsignaturas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 230, 196, 237));

        jButton1.setText("Ofertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 305, 75, -1));

        jButton2.setText("Quitar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 339, 75, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// TODO add your handling code here:
  this.setVisible(false);
  this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        int i = lstAsignaturas.getSelectedIndex();        
        if (i > -1){                    
            Asignaturas a1 = (Asignaturas) lstAsignaturas.getSelectedValue();
            id_asignatura = a1.getIdAsignatura();
            guardar();
        }
    
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        int i = lstOfertaAsignaturas.getSelectedIndex();
        OfertaAcademica a = (OfertaAcademica) lstOfertaAsignaturas.getSelectedValue();
        if (i > -1){            
            try {
                oferta.deleteOfertaAcademica(a.getIdOfertaAcademica());
                updateListOfertaAsignaturas();
            } catch (SQLException ex) {
                Logger.getLogger(frmOfertaAcademica.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmOfertaAcademica.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    
}//GEN-LAST:event_jButton2ActionPerformed


  private void cargaDatos(){
      
      id_grupo = g.getIdGrupo();      
      id_generacion = g.getIdGeneracion();
      id_carrera = g.getIdCarrera();
      id_plan = g.getIdPlan();
      semestre = g.getSemestre();
      
      this.lblCicloEscolar.setText(g.getCiclo().getPeriodo());
      this.lblGeneracion.setText(g.getGeneracion().getNombre());
      this.lblCarrera.setText(g.getCarrera().getNombre());      
      this.lblArea.setText(g.getArea().getDescripcion());            
      
      this.lblSemestre.setText(g.getSemestre().toString());
      this.lblGrupo.setText(g.getGrupo());      
            
      //this.lblCicloEscolar.setText(g.getCiclo().getPeriodo());
      
//      this.lblCicloEscolar.setText(g.getC);
      
  }

  private  void guardar(){
        try {
            oa.setIdOfertaAcademica(0);
            oa.setIdGrupo(id_grupo);
            oa.setIdAsignatura(id_asignatura);
            oa.setIdPersonal(0);
            oferta.setOfertaAcademica(oa,0);
            updateListOfertaAsignaturas();
        } catch (SQLException ex) {
            //Error de clave duplicada
            if (ex.getErrorCode() == 1062) {
                JOptionPane.showMessageDialog(this, "La asignatura ya ha sido ofertada");
            }else{
                Logger.getLogger(frmOfertaAcademica.class.getName()).log(Level.SEVERE, null, ex);                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmOfertaAcademica.class.getName()).log(Level.SEVERE, null, ex);
        }
  }
  
  private void updateComboGrupos() {
         ctrlGrupos gr = new ctrlGrupos();
         ArrayList<Grupos> lista = new ArrayList<Grupos>();
         try {
            lista = gr.getGrupos(0, 0, 0, 0, 0); //Mostrar todos los grupos
            DefaultComboBoxModel modeloCombo;         
            modeloCombo =  new DefaultComboBoxModel();
            modeloCombo.removeAllElements();
            modeloCombo = gr.getComboGruposGeneracion(lista);
            //cmbGrupo.setModel(modeloCombo);                    
           
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());                               
         }
  }
  
  private void updateListAsignaturas() {
         ctrlAsignaturas a = new ctrlAsignaturas();
         ArrayList<Asignaturas> lista = new ArrayList<Asignaturas>();
         try {
            lista = a.getAsignaturas(id_carrera, semestre);
            DefaultListModel modeloLista;         
            modeloLista =  new DefaultListModel();
            modeloLista.removeAllElements();
            modeloLista = a.getListAsignaturas(lista);
            lstAsignaturas.setModel(modeloLista);                    
           
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());                               
         }
  }
  

  private void updateListOfertaAsignaturas() {
         ctrlOfertaAcademica o = new ctrlOfertaAcademica();
         ArrayList<OfertaAcademica> lista = new ArrayList<OfertaAcademica>();
         try {
            lista = o.getOfertaAcademica(id_grupo, 1);
            DefaultListModel modeloLista;         
            modeloLista =  new DefaultListModel();
            modeloLista.removeAllElements();
            modeloLista = o.getListOfertaAcademica(lista);
            lstOfertaAsignaturas.setModel(modeloLista);                    
           
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, "error" + e.getMessage());                               
         }
  }
  
  
  
  

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmOfertaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmOfertaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmOfertaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmOfertaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmOfertaAcademica dialog = new frmOfertaAcademica(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCicloEscolar;
    private javax.swing.JLabel lblGeneracion;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblSemestre;
    private javax.swing.JList lstAsignaturas;
    private javax.swing.JList lstOfertaAsignaturas;
    // End of variables declaration//GEN-END:variables
}
