/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;


import Controladores.JCheckBoxCellRenderer;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import Controladores.MyTableModel;
import Controladores.PermisosTableModel;
import Controladores.ctrlOfertaAcademica;
import Controladores.ctrlPermisosUsuario;
import Entidades.Usuarios;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leonel
 */
public class frmPermisosUsuario extends javax.swing.JDialog {

    public static String docente;
    
    /**
     * Creates new form frmCargaAcademicaDocentes
     */
    
    public frmPermisosUsuario(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public frmPermisosUsuario(java.awt.Dialog parent, boolean modal, Usuarios user) {
        super(parent, modal);
        initComponents();
        updateTabla(user.getId_usuario());
        //this.jLabel1.setText("Gestión del Permisos del Usuario: " + user.getUsuario());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 12));
        jLabel1.setText("Gestión de Permisos");

        tabla.setAutoCreateRowSorter(true);
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnSalir.setText("Cancelar");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 295, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        int fila = tabla.rowAtPoint(evt.getPoint());                 
        int col = tabla.columnAtPoint(evt.getPoint());
        if (col == 6) {
            docente = "";
            //JOptionPane.showMessageDialog(this, "fila = " + fila + " columna = " + col);
            frmListaPersonal1 frm = new frmListaPersonal1(this,true);
            frm.setLocationRelativeTo(frm);
            frm.setVisible(true);
            
            if (!"".equals(docente)) {
                String[] p = docente.split(",");
                tabla.setValueAt(p[0], fila, 4); //Columna Id del docente            
                tabla.setValueAt(p[1], fila, 5); //Columna nombre del docente
            }
            //JOptionPane.showMessageDialog(this, "seleccionado = " + id_docente);
            
        }
        
        
    }//GEN-LAST:event_tablaMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
      if (JOptionPane.showConfirmDialog(this, "¿Deseas guardar los cambios?") == JOptionPane.YES_OPTION) {        
            try {
                guardar();
              //JOptionPane.showMessageDialog(this, "Los cambios fueron realizados con éxito");             
              //this.setVisible(false);          
              //this.dispose();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmPermisosUsuario.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(frmPermisosUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void updateTabla(int id_usuario){
        try {
            //String[] titulos = {"id_permiso","Descripcion","permitido"};  

            ctrlPermisosUsuario cusuario = new ctrlPermisosUsuario();
            PermisosTableModel datos = new PermisosTableModel();

            //datos.setColumnIdentifiers(titulos);
            datos=cusuario.getPermisos(cusuario.getPermisos(id_usuario));
            tabla.setModel(datos);
            TableColumn columna;
            columna = tabla.getColumn("id_permiso");                    
            columna.setPreferredWidth(0);
            columna.setMinWidth(0);
            columna.setMaxWidth(0);            
//            columna = tabla.getColumn("Descripcion");                    
//            columna.setPreferredWidth(200);
//            columna.setMinWidth(200);
//            columna.setMaxWidth(300);
            columna = tabla.getColumn("permitido");                    
            columna.setPreferredWidth(100);
            columna.setMinWidth(100);
            columna.setMaxWidth(100);                        

        } catch (SQLException ex) {
            Logger.getLogger(frmPermisosUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPermisosUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
  private  void guardar() throws ClassNotFoundException, SQLException{
      
      ctrlOfertaAcademica carga = new ctrlOfertaAcademica();          
      boolean result;
      result = carga.setOfertaAcademica(tabla.getModel());
      

      if (result){
        JOptionPane.showMessageDialog(this, "Los cambios fueron realizados exitosamente");                                  
      }else{
        JOptionPane.showMessageDialog(this, "El ciclo escolar no pudo agregarse debido a un problema");                    
      }
      
      
  }
    
    /**
     * @param args the command line arguments
     */
      
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmPermisosUsuario dialog = new frmPermisosUsuario(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
