/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPagos.java
 *
 * Created on 1/02/2012, 11:44:40 AM
 */
package Formularios;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import Controladores.JLabelCellRenderer;
import Controladores.ctrlAlumnos;
import Controladores.ctrlPagos;
import Controladores.ctrlGrupos;
import Entidades.Alumnos;
import Entidades.Pagos;
import Entidades.Partidas;
import Entidades.Recibo;
import Entidades.Grupos;

/**
 *
 * @author leonel
 */
public class frmPagos extends javax.swing.JDialog {

    public static Alumnos alumno;
    Pagos pago = new Pagos();
    ctrlPagos cpago = new ctrlPagos();
    public static Partidas p;
    private DefaultTableModel m;

    /** Creates new form frmPagos */
    public frmPagos(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //this.txtIdAlumno.setVisible(false);
        nuevo();
    }

    private void nuevo() {
        Date hoy = new Date();
        this.dpFecha.setFormats("dd-MM-yyyy");
        this.dpFecha.setDate(hoy);
        //this.updateTabla();       
        this.txtMatricula.setText("");
        this.txtIdAlumno.setVisible(false);
        this.txtIdAlumno.setText("");
        this.lblNombre.setText("");
        this.lblApellidoPaterno.setText("");
        this.lblApellidoMaterno.setText("");
        this.lblTotal.setText("0.00");
        this.lblTotal.setHorizontalAlignment(SwingConstants.RIGHT);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        dpFecha = new org.jdesktop.swingx.JXDatePicker();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblSemestre = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtIdAlumno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Formularios/Bundle"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), bundle.getString("frmPagos.jPanel1.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel2.setText(bundle.getString("frmPagos.jLabel2.text")); // NOI18N

        jLabel3.setText(bundle.getString("frmPagos.jLabel3.text")); // NOI18N

        txtMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatriculaActionPerformed(evt);
            }
        });
        txtMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMatriculaKeyReleased(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), bundle.getString("frmPagos.jPanel2.border.title"), javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel7.setText(bundle.getString("frmPagos.jLabel7.text")); // NOI18N

        jLabel9.setText(bundle.getString("frmPagos.jLabel9.text")); // NOI18N

        jLabel10.setText(bundle.getString("frmPagos.jLabel10.text")); // NOI18N

        lblNombre.setText(bundle.getString("frmPagos.lblNombre.text")); // NOI18N

        lblApellidoPaterno.setText(bundle.getString("frmPagos.lblApellidoPaterno.text")); // NOI18N

        lblApellidoMaterno.setText(bundle.getString("frmPagos.lblApellidoMaterno.text")); // NOI18N

        jLabel11.setText(bundle.getString("frmPagos.jLabel11.text")); // NOI18N

        lblDomicilio.setText(bundle.getString("frmPagos.lblDomicilio.text")); // NOI18N

        jLabel12.setText(bundle.getString("frmPagos.jLabel12.text")); // NOI18N

        lblSemestre.setText(bundle.getString("frmPagos.lblSemestre.text")); // NOI18N

        jLabel13.setText(bundle.getString("frmPagos.jLabel13.text")); // NOI18N

        lblGrupo.setText(bundle.getString("frmPagos.lblGrupo.text")); // NOI18N

        jLabel14.setText(bundle.getString("frmPagos.jLabel14.text")); // NOI18N

        lblTurno.setText(bundle.getString("frmPagos.lblTurno.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellidoPaterno)
                    .addComponent(lblApellidoMaterno)
                    .addComponent(lblNombre)
                    .addComponent(lblDomicilio)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSemestre)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel13)
                        .addGap(53, 53, 53)
                        .addComponent(lblGrupo)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel14)
                        .addGap(53, 53, 53)
                        .addComponent(lblTurno)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblApellidoPaterno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblApellidoMaterno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblDomicilio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblSemestre)
                    .addComponent(jLabel13)
                    .addComponent(lblGrupo)
                    .addComponent(jLabel14)
                    .addComponent(lblTurno))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton1.setText(bundle.getString("frmPagos.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Clave", "Concepto", "Importe", "Cantidad", "Subtotal"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel8.setText(bundle.getString("frmPagos.jLabel8.text")); // NOI18N

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText(bundle.getString("frmPagos.btnGuardar.text")); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        btnSalir.setText(bundle.getString("frmPagos.btnSalir.text")); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAgregar.setText(bundle.getString("frmPagos.btnAgregar.text")); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setText(bundle.getString("frmPagos.btnQuitar.text")); // NOI18N
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        lblTotal.setText(bundle.getString("frmPagos.lblTotal.text")); // NOI18N
        lblTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 0, 0, 0));

        txtIdAlumno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtIdAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 394, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, 12))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAgregar, btnQuitar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnAgregar)
                    .addComponent(btnQuitar)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalir)
                            .addComponent(btnGuardar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtIdAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_tablaMouseClicked

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
// TODO add your handling code here:
    //System.out.println("se ha pulsado guardar");
    this.guardar();
}//GEN-LAST:event_btnGuardarActionPerformed

private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                       
                
        alumno = null;

        frmListaAlumnos1 frmalumnos = new frmListaAlumnos1(this, true);
        frmalumnos.setLocationRelativeTo(this);
        frmalumnos.setVisible(true);

        if (alumno.getNombre() != null) {
            lblNombre.setText(alumno.getNombre());
            lblApellidoPaterno.setText(alumno.getApePaterno());
            lblApellidoMaterno.setText(alumno.getApeMaterno());
            lblDomicilio.setText(alumno.getDireccion());    
            txtMatricula.setText(alumno.getMatricula());

            
            

           ctrlGrupos ctrlgrupo = new ctrlGrupos();
            try {
                Grupos grupo = ctrlgrupo.getGrupos(alumno.getGrupo().getIdGrupo());
            } catch (SQLException ex) {
                Logger.getLogger(frmPagos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmPagos.class.getName()).log(Level.SEVERE, null, ex);
            }
           
            
            lblSemestre.setText(alumno.getGrupo().getSemestre().toString());
            lblGrupo.setText(alumno.getGrupo().getGrupo());            
            lblTurno.setText(alumno.getGrupo().getTurno());
            
            
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatriculaKeyReleased
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_ENTER)) {
            try {

                ctrlAlumnos ctrlalumno = new ctrlAlumnos();
                ArrayList<Alumnos> lista = null;
                Alumnos objalumno;
                //Se modificó el procedimiento almacenado, agregándose un criterio de selección
                //Realizado por leonel el 7 de abril de 2012
                lista = ctrlalumno.getFiltroPersonal("MatriculaUno", this.txtMatricula.getText());
                if (lista.size() > 0) {
                    this.txtIdAlumno.setText("");
                    this.lblNombre.setText("");
                    this.lblApellidoPaterno.setText("");
                    this.lblApellidoMaterno.setText("");
                    objalumno = lista.get(0);
                    this.txtIdAlumno.setText(String.valueOf(objalumno.getIdAlumno()));
                    this.lblNombre.setText(objalumno.getNombre());
                    this.lblApellidoPaterno.setText(objalumno.getApePaterno());
                    this.lblApellidoMaterno.setText(objalumno.getApeMaterno());
                } else {
                    this.txtIdAlumno.setText("");
                    this.lblNombre.setText("");
                    this.lblApellidoPaterno.setText("");
                    this.lblApellidoMaterno.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmPagos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmPagos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtMatriculaKeyReleased

    
   
        private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
            // TODO add your handling code here:
            agregarPartida();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
        quitarPartida();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void txtMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatriculaActionPerformed

    private void updateTabla() {
        try {
            //String titulos[] = {"Clave", "Concepto","Importe","Cantidad","Subtotal"};
            //m = new MyTableModel(null,titulos);

            m = new DefaultTableModel();
            m = cpago.getDetallePagos(cpago.getDetallePagos(0));

            tabla.setModel(m);
            TableColumn columna;
            columna = tabla.getColumn("Clave");
            columna.setPreferredWidth(80);
            columna.setMinWidth(80);
            columna.setMaxWidth(80);

            columna = tabla.getColumn("Concepto");
            columna.setPreferredWidth(200);
            columna.setMinWidth(200);
            columna.setMaxWidth(200);


            //Alineación de celdas
            //MyTableCellRenderer celda = new MyTableCellRenderer();
            //celda.setHorizontalAlignment(SwingConstants.RIGHT);


            tabla.getColumn("Importe").setCellRenderer(new JLabelCellRenderer());
            tabla.getColumn("Cantidad").setCellRenderer(new JLabelCellRenderer());
            tabla.getColumn("Subtotal").setCellRenderer(new JLabelCellRenderer());

            // Install the custom renderer on the first visible column
            //int vColIndex = 0;
            //TableColumn col = table.getColumnModel().getColumn(vColIndex);
            //col.setCellRenderer(new MyTableCellRenderer());        

            //agregarPartida();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPagos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmPagos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void agregarPartida() {
        if (tabla.getRowCount() < 5) {
            p = null;
            frmPartidas1 frmpartidas = new frmPartidas1(this, true);
            frmpartidas.setLocationRelativeTo(this);
            frmpartidas.setVisible(true);
            if (p != null) {
                m = (DefaultTableModel) tabla.getModel();
                String partida[] = new String[6];
                partida[0] = p.getIdCuenta();
                partida[1] = p.getDescripcion();
                partida[2] = String.valueOf(p.getImporte());
                int cantidad = 1;
                partida[3] = String.valueOf(cantidad);
                float subtotal = p.getImporte() * cantidad;
                partida[4] = String.valueOf(subtotal);
                m.addRow(partida);
                formatTotal();
            } else {
                p = null;
            }
        }
    }

    private void quitarPartida() {
        int fila = tabla.getSelectedRow();
        if (fila > -1) {
            if (JOptionPane.showConfirmDialog(this, "¿Deseas eliminar esta partida?") == JOptionPane.YES_OPTION) {
                m = (DefaultTableModel) tabla.getModel();
                m.removeRow(fila);
                formatTotal();
            }
        }
    }

    private void formatTotal() {
        NumberFormat formatter = new DecimalFormat("#,##0.00");
        lblTotal.setText(formatter.format(getTotal()));
    }

    private float getTotal() {
        float total = 0;
        for (int i = 0; i <= tabla.getRowCount() - 1; i++) {
            total += Float.parseFloat(tabla.getValueAt(i, 4).toString());
        }
        return total;
    }

    private void guardar() {
        try {
            if (validar()) {
                if (JOptionPane.showConfirmDialog(this, "¿Deseas guardar los cambios?") == JOptionPane.YES_OPTION) {
                    pago.setIdPago(0);
                    String fecha = String.valueOf(dpFecha.getEditor().getText());
                    pago.setFecha(fecha);
                    pago.setIdAlumno(Integer.parseInt(txtIdAlumno.getText()));
                    pago.setIdUsuario(frmPrincipal.usuarioActual.getId_usuario());
                    pago.setImporteTotal(getTotal());
                    pago.setObservaciones("");
                    imprimirRecibo();
                    this.dispose();
                    boolean result = cpago.setPago(pago, tabla.getModel());                    

                    
                    if (result) {
                        
                        JOptionPane.showMessageDialog(this, "Los cambios fueron realizados exitosamente");
                        this.setVisible(result);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "El pago no pudo agregarse debido a un problema");
                    }
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmPagos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPagos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void imprimirRecibo() {
        
        long lnMilisegundos = dpFecha.getDate().getTime();
        java.sql.Date fecha = new java.sql.Date(lnMilisegundos);
        String[] f = fecha.toString().split("-");
        
        Recibo recibo=null;

        recibo.setFolio(0); //El folio será capturado por el cajero
        
        recibo.setAnio(Integer.parseInt(f[0]));
        recibo.setMes(Integer.parseInt(f[1]));
        recibo.setDia(Integer.parseInt(f[2])); 
        recibo.setEntidadFederativa("Yucatán");
        recibo.setRfc("0000000000000");
        
        recibo.setMatricula(txtMatricula.getText());
        recibo.setNombre(lblNombre.getText());
        recibo.setApepat(lblApellidoPaterno.getText());
        recibo.setApemat(lblApellidoMaterno.getText());
        recibo.setDomicilio(lblDomicilio.getText());
        
        
        
        
        
        
        
    }

    private boolean validar() {
        boolean result = false;


        if ("".equals(this.txtIdAlumno.getText())) {
            JOptionPane.showMessageDialog(this, "Escribe la matricula del alumno");
        } else if (m.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(this, "No has agregardo ninguna partida");
        } else {
            result = true;
        }

        return result;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmPagos dialog = new frmPagos(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton btnAgregar;
    javax.swing.JButton btnGuardar;
    javax.swing.JButton btnQuitar;
    javax.swing.JButton btnSalir;
    org.jdesktop.swingx.JXDatePicker dpFecha;
    javax.swing.JButton jButton1;
    javax.swing.JLabel jLabel10;
    javax.swing.JLabel jLabel11;
    javax.swing.JLabel jLabel12;
    javax.swing.JLabel jLabel13;
    javax.swing.JLabel jLabel14;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JLabel jLabel7;
    javax.swing.JLabel jLabel8;
    javax.swing.JLabel jLabel9;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JLabel lblApellidoMaterno;
    javax.swing.JLabel lblApellidoPaterno;
    javax.swing.JLabel lblDomicilio;
    javax.swing.JLabel lblGrupo;
    javax.swing.JLabel lblNombre;
    javax.swing.JLabel lblSemestre;
    javax.swing.JLabel lblTotal;
    javax.swing.JLabel lblTurno;
    javax.swing.JTable tabla;
    javax.swing.JLabel txtIdAlumno;
    javax.swing.JTextField txtMatricula;
    // End of variables declaration//GEN-END:variables
}
