/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPartidas.java
 *
 * Created on 08-dic-2011, 12:32:24
 */
package Formularios;

import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import Controladores.ctrlPartidas;
import Entidades.Partidas;

/**
 *
 * @author Last Develop
 */
public class frmPartidas1 extends javax.swing.JDialog {
ctrlPartidas ctrlpartida=new ctrlPartidas();
ArrayList<Partidas> lista=null;
Partidas partidaPadre=null;
Partidas partidaHijo=null;
    /** Creates new form frmPartidas */
    public frmPartidas1(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Updateform();
       this.itemAgregar.setText("Agregar");
        //this.jPanel2.setVisible(false);
        this.treePartidas.setRootVisible(false);
        
    }
private void Updateform()
{
  this.treePartidas.getSelectionModel().setSelectionMode(javax.swing.tree.TreeSelectionModel.SINGLE_TREE_SELECTION);
        lista=ctrlpartida.getGruposPartidas("0");
        this.treePartidas.setModel(ctrlpartida.getGrupos(lista));
        //this.cmbGrupo.setModel(ctrlpartida.getModeloCombo(lista));
}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupArbol = new javax.swing.JPopupMenu();
        itemAgregar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        treePartidas = new javax.swing.JTree();

        itemAgregar.setText("jMenuItem1");
        itemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarActionPerformed(evt);
            }
        });
        popupArbol.add(itemAgregar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de Partidas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        treePartidas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treePartidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                treePartidasMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                treePartidasMousePressed(evt);
            }
        });
        treePartidas.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treePartidasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(treePartidas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void treePartidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treePartidasMouseClicked
 // TODO add your handling code here:
    try{
      DefaultMutableTreeNode nodo=(DefaultMutableTreeNode) this.treePartidas.getLastSelectedPathComponent();
      this.partidaPadre=(Partidas) nodo.getUserObject();      
      //this.cmbGrupo.setSelectedItem(partidaPadre.getDescripcion());
    }
    catch(Exception ex)
    {
    System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_treePartidasMouseClicked

private void treePartidasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_treePartidasMousePressed
 // TODO add your handling code here:
    
    if(evt.getButton()==MouseEvent.BUTTON3)
    {
     this.popupArbol.show(this.treePartidas,evt.getX(),evt.getY());
    }
}//GEN-LAST:event_treePartidasMousePressed

private void treePartidasValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treePartidasValueChanged
 // TODO add your handling code here:
   /* try{
    DefaultMutableTreeNode nodo=(DefaultMutableTreeNode) this.treePartidas.getLastSelectedPathComponent();
      this.partidaPadre=(Partidas) nodo.getUserObject();
      
      //this.cmbGrupo.setSelectedItem(partidaPadre.getDescripcion());
    }
    catch(Exception ex)
    {
    //System.out.println(ex.getMessage());
    }*/
        
         
    
}//GEN-LAST:event_treePartidasValueChanged

private void itemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarActionPerformed
 // TODO add your handling code here:
      DefaultMutableTreeNode nodo=(DefaultMutableTreeNode) this.treePartidas.getLastSelectedPathComponent();
      partidaPadre=(Partidas) nodo.getUserObject();      
      //JOptionPane.showMessageDialog(this, partidaPadre.getImporte());
      frmPagos.p = partidaPadre;
    this.setVisible(false);
    this.dispose();
    //Updateform();
}//GEN-LAST:event_itemAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPartidas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPartidas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPartidas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPartidas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                frmPartidas1 dialog = new frmPartidas1(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemAgregar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu popupArbol;
    private javax.swing.JTree treePartidas;
    // End of variables declaration//GEN-END:variables
}
