/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPrincipal.java
 *
 * Created on 07-dic-2011, 20:00:09
 */
package Formularios;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import Controladores.ctrlPermisosUsuario;
import Entidades.Personal;
import Entidades.Usuarios;

/**
 *
 * @author Last Develop
 */
public class frmPrincipal extends javax.swing.JFrame {
    private Personal personal;
    private Usuarios sesion;
    public static Usuarios usuarioActual;
    
    private  final  jpfondo fondo=new jpfondo();
    private frmPrincipal() {
        
    }

    public Personal getPersonal() {
        return personal;
    }

    public void setPersonal(Personal personal) {
        this.personal = personal;
    }

    /** Creates new form frmPrincipal */
    public frmPrincipal(Personal personal, Usuarios usuario) {
        try {
            
            initComponents();
            
            String ruta=System.getProperty("user.dir");
            String archivo=ruta+"\\src\\Imagenes\\fondo1.jpg";

            
            
            fondo.setImagen(archivo);
            this.setContentPane(fondo);
            this.personal=personal;
            this.usuarioActual = usuario;
            String titulo = "SICE Versión 1.0 - ";
            if (this.personal.getNombre()==null){
                titulo += "Usuario Conectado: " + usuario.getUsuario();
            }else{
                titulo += "Usuario Conectado: " + this.personal.getNombre() + " " + this.personal.getApePaterno();
            }
            this.setTitle(titulo);
            sesion = new Usuarios();
            sesion.setId_usuario(usuario.getId_usuario());
            this.vistaUsuario(usuario.getId_usuario());
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        smnuRegistrar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        smnuinscripciones = new javax.swing.JMenuItem();
        smnuBajasAlumnos = new javax.swing.JMenuItem();
        smnuAjusteCargaAcademica = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        smnuPuestos = new javax.swing.JMenuItem();
        smnuProfesores = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mnuGrupos = new javax.swing.JMenu();
        smnuGestionGrupos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        smnuRegistrarCalificaciones = new javax.swing.JMenuItem();
        smnuparcialesmaestro = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        smnuGestionCiclos = new javax.swing.JMenuItem();
        smnuActivarCiclos = new javax.swing.JMenuItem();
        smnuCerrarSemestre = new javax.swing.JMenuItem();
        smnuPlanes = new javax.swing.JMenuItem();
        smnuCarreras = new javax.swing.JMenuItem();
        smnuModulos = new javax.swing.JMenuItem();
        smnuAsignaturas = new javax.swing.JMenuItem();
        smnuUnidadAprendizaje = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        smnuPartidas = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        smnuRedis = new javax.swing.JMenuItem();
        smnuRevas = new javax.swing.JMenuItem();
        smnuListaAsistencia = new javax.swing.JMenuItem();
        smnuRexas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        smnuEscuela = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        smnuGestionUsuarios = new javax.swing.JMenuItem();

        jMenu9.setText("File");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar2.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar3.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar3.add(jMenu12);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Control Escolar V. 1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inscripcion.png"))); // NOI18N
        jMenu1.setText("ALUMNOS");

        smnuRegistrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        smnuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registro_alumnos.png"))); // NOI18N
        smnuRegistrar.setText("Registrar");
        smnuRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuRegistrarActionPerformed(evt);
            }
        });
        jMenu1.add(smnuRegistrar);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver_kardex.png"))); // NOI18N
        jMenuItem2.setText("Historial Académico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        smnuinscripciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inscripcion.png"))); // NOI18N
        smnuinscripciones.setText("Inscripciones/Reinscripción");
        smnuinscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuinscripcionesActionPerformed(evt);
            }
        });
        jMenu1.add(smnuinscripciones);

        smnuBajasAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baja_alumnos.png"))); // NOI18N
        smnuBajasAlumnos.setText("Bajas");
        smnuBajasAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuBajasAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(smnuBajasAlumnos);

        smnuAjusteCargaAcademica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ajuste_carga.png"))); // NOI18N
        smnuAjusteCargaAcademica.setText("Ajuste de Carga Académica");
        smnuAjusteCargaAcademica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuAjusteCargaAcademicaActionPerformed(evt);
            }
        });
        jMenu1.add(smnuAjusteCargaAcademica);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/profesores.png"))); // NOI18N
        jMenu2.setText("MAESTROS");

        smnuPuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modulo.png"))); // NOI18N
        smnuPuestos.setText("Puestos");
        smnuPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuPuestosActionPerformed(evt);
            }
        });
        jMenu2.add(smnuPuestos);

        smnuProfesores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        smnuProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/profesores.png"))); // NOI18N
        smnuProfesores.setText("Lista Maestros");
        smnuProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuProfesoresActionPerformed(evt);
            }
        });
        jMenu2.add(smnuProfesores);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carga_academica.png"))); // NOI18N
        jMenuItem4.setText("Asignar Carga Academica");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        mnuGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carga_academica.png"))); // NOI18N
        mnuGrupos.setText("GRUPOS");
        mnuGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGruposActionPerformed(evt);
            }
        });

        smnuGestionGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carga_academica.png"))); // NOI18N
        smnuGestionGrupos.setText("Gestión de Grupos");
        smnuGestionGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuGestionGruposActionPerformed(evt);
            }
        });
        mnuGrupos.add(smnuGestionGrupos);

        jMenuBar1.add(mnuGrupos);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        jMenu5.setText("CALIFICACIONES");

        smnuRegistrarCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/editar.png"))); // NOI18N
        smnuRegistrarCalificaciones.setText("Registrar Parciales");
        smnuRegistrarCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuRegistrarCalificacionesActionPerformed(evt);
            }
        });
        jMenu5.add(smnuRegistrarCalificaciones);

        smnuparcialesmaestro.setText("Registrar Parciales Maestro");
        smnuparcialesmaestro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuparcialesmaestroActionPerformed(evt);
            }
        });
        jMenu5.add(smnuparcialesmaestro);

        jMenuBar1.add(jMenu5);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administracion.png"))); // NOI18N
        jMenu4.setText("ADMINISTRACIÓN");

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ciclo_escolar.png"))); // NOI18N
        jMenu8.setText("Semestres");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        smnuGestionCiclos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gestionar_ciclo.png"))); // NOI18N
        smnuGestionCiclos.setText("Gestión de Semestres");
        smnuGestionCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuGestionCiclosActionPerformed(evt);
            }
        });
        jMenu8.add(smnuGestionCiclos);

        smnuActivarCiclos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/activar_ciclo.png"))); // NOI18N
        smnuActivarCiclos.setText("Activar Semestre Actual");
        smnuActivarCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuActivarCiclosActionPerformed(evt);
            }
        });
        jMenu8.add(smnuActivarCiclos);

        smnuCerrarSemestre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar_ciclo.png"))); // NOI18N
        smnuCerrarSemestre.setText("Cerrar Semestre Actual");
        smnuCerrarSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuCerrarSemestreActionPerformed(evt);
            }
        });
        jMenu8.add(smnuCerrarSemestre);

        jMenu4.add(jMenu8);

        smnuPlanes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/plan.png"))); // NOI18N
        smnuPlanes.setText("Planes");
        smnuPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuPlanesActionPerformed(evt);
            }
        });
        jMenu4.add(smnuPlanes);

        smnuCarreras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrera.png"))); // NOI18N
        smnuCarreras.setText("Carreras");
        smnuCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuCarrerasActionPerformed(evt);
            }
        });
        jMenu4.add(smnuCarreras);

        smnuModulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modulo.png"))); // NOI18N
        smnuModulos.setText("Módulos");
        smnuModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuModulosActionPerformed(evt);
            }
        });
        jMenu4.add(smnuModulos);

        smnuAsignaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asignatura.png"))); // NOI18N
        smnuAsignaturas.setText("Asignaturas / Submódulos");
        smnuAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuAsignaturasActionPerformed(evt);
            }
        });
        jMenu4.add(smnuAsignaturas);

        smnuUnidadAprendizaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/unidad_aprendizaje.png"))); // NOI18N
        smnuUnidadAprendizaje.setText("Unidades de Aprendizaje");
        smnuUnidadAprendizaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuUnidadAprendizajeActionPerformed(evt);
            }
        });
        jMenu4.add(smnuUnidadAprendizaje);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pagos.png"))); // NOI18N
        jMenu6.setText("COBRANZA");

        smnuPartidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/partidas.png"))); // NOI18N
        smnuPartidas.setText("Partidas");
        smnuPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuPartidasActionPerformed(evt);
            }
        });
        jMenu6.add(smnuPartidas);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pagos.png"))); // NOI18N
        jMenuItem9.setText("Pagos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuBar1.add(jMenu6);

        mnuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/printer.png"))); // NOI18N
        mnuReportes.setText("REPORTES");
        mnuReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReportesActionPerformed(evt);
            }
        });

        smnuRedis.setText("REDIS");
        smnuRedis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuRedisActionPerformed(evt);
            }
        });
        mnuReportes.add(smnuRedis);

        smnuRevas.setText("REVAS");
        smnuRevas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuRevasActionPerformed(evt);
            }
        });
        mnuReportes.add(smnuRevas);

        smnuListaAsistencia.setText("Lista de Asistencia");
        smnuListaAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuListaAsistenciaActionPerformed(evt);
            }
        });
        mnuReportes.add(smnuListaAsistencia);

        smnuRexas.setText("REXAS");
        mnuReportes.add(smnuRexas);

        jMenuBar1.add(mnuReportes);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png"))); // NOI18N
        jMenu7.setText("CONFIGURACIÓN");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        smnuEscuela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        smnuEscuela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/escuela.png"))); // NOI18N
        smnuEscuela.setText("Escuela");
        smnuEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuEscuelaActionPerformed(evt);
            }
        });
        jMenu7.add(smnuEscuela);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/configuracion.png"))); // NOI18N
        jMenuItem5.setText("Parámetros del Reporte");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem5);

        smnuGestionUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        smnuGestionUsuarios.setText("Gestión de Usuarios");
        smnuGestionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuGestionUsuariosActionPerformed(evt);
            }
        });
        jMenu7.add(smnuGestionUsuarios);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void smnuPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuPuestosActionPerformed
 // TODO add your handling code here:
   frmPuestos puestos=new frmPuestos(this,true) ;
   puestos.setLocationRelativeTo(this);
   puestos.setVisible(true);
    
}//GEN-LAST:event_smnuPuestosActionPerformed

private void smnuRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuRegistrarActionPerformed
 // TODO add your handling code here:
    frmListaAlumnos listaalumnos=new frmListaAlumnos(this,true);
    listaalumnos.setLocationRelativeTo(this);
    listaalumnos.setVisible(true);
}//GEN-LAST:event_smnuRegistrarActionPerformed

private void smnuProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuProfesoresActionPerformed
 // TODO add your handling code here:
    frmListaPersonal listapersonal=new frmListaPersonal(this,true);
    listapersonal.setLocationRelativeTo(this);
    listapersonal.setVisible(true);
}//GEN-LAST:event_smnuProfesoresActionPerformed

private void smnuEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuEscuelaActionPerformed
 // TODO add your handling code here:
    frmEscuela escuela=new frmEscuela(this,true);
    escuela.setLocationRelativeTo(this);
    escuela.setVisible(true);
}//GEN-LAST:event_smnuEscuelaActionPerformed

private void smnuPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuPartidasActionPerformed
 // TODO add your handling code here:
    frmPartidas partidas=new frmPartidas(this, true);
    
    partidas.setLocationRelativeTo(this);
    partidas.setVisible(true);
}//GEN-LAST:event_smnuPartidasActionPerformed

private void smnuGestionCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuGestionCiclosActionPerformed
 // TODO add your handling code here:
    frmCiclos frmciclos=new frmCiclos(this,true);
    frmciclos.setLocationRelativeTo(this);
    frmciclos.setVisible(true);
    
}//GEN-LAST:event_smnuGestionCiclosActionPerformed

private void smnuActivarCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuActivarCiclosActionPerformed
 // TODO add your handling code here:
   frmActivarCiclo frmactivarciclos=new frmActivarCiclo();
   frmactivarciclos.setLocationRelativeTo(this);
   frmactivarciclos.setVisible(true);
    
}//GEN-LAST:event_smnuActivarCiclosActionPerformed

private void smnuCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuCarrerasActionPerformed
 // TODO add your handling code here:
    frmCarreras frmcarreras=new frmCarreras(this,true);
    frmcarreras.setLocationRelativeTo(this);
    frmcarreras.setVisible(true);
}//GEN-LAST:event_smnuCarrerasActionPerformed

private void smnuPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuPlanesActionPerformed
 // TODO add your handling code here:
    frmPlanes frmplanes = new frmPlanes(this,true);
    frmplanes.setLocationRelativeTo(this);
    frmplanes.setVisible(true);
      
    
}//GEN-LAST:event_smnuPlanesActionPerformed

private void smnuAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuAsignaturasActionPerformed
 // TODO add your handling code here:
    frmListaAsignaturas frmasignaturas=new frmListaAsignaturas(this,true);
    frmasignaturas.setLocationRelativeTo(this);    
    frmasignaturas.setVisible(true);
}//GEN-LAST:event_smnuAsignaturasActionPerformed

private void mnuGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGruposActionPerformed
 // TODO add your handling code here:
 
}//GEN-LAST:event_mnuGruposActionPerformed

private void smnuGestionGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuGestionGruposActionPerformed
 // TODO add your handling code here:
       frmListaGrupos frmgrupos =new frmListaGrupos(this,true);
       frmgrupos.setLocationRelativeTo(this);
    frmgrupos.setVisible(true);
}//GEN-LAST:event_smnuGestionGruposActionPerformed

private void smnuinscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuinscripcionesActionPerformed
        try {
            // TODO add your handling code here:
               dlgBuscarAlumno buscaralumno=new dlgBuscarAlumno(this,true);
               buscaralumno.setLocationRelativeTo(this);
               buscaralumno.setUsuario(sesion);
                  buscaralumno.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}//GEN-LAST:event_smnuinscripcionesActionPerformed

private void smnuRegistrarCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuRegistrarCalificacionesActionPerformed
        try {
            // TODO add your handling code here:
               frmRegistrarCalificaciones dlgcalificaciones=new frmRegistrarCalificaciones(this,true);
               dlgcalificaciones.setLocationRelativeTo(this);
               dlgcalificaciones.setUsuario(sesion);
               dlgcalificaciones.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_smnuRegistrarCalificacionesActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            // TODO add your handling code here:
               dlgBuscarAlumnokardex dlgbuscar=new dlgBuscarAlumnokardex(this,false);
               dlgbuscar.setLocationRelativeTo(null);
               dlgbuscar.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void smnuRedisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuRedisActionPerformed
        try {
            // TODO add your handling code here:
               frmGenerarReportes generarreporte=new frmGenerarReportes(this,false);
               generarreporte.setVisible(true);
               generarreporte.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    
}//GEN-LAST:event_smnuRedisActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
// TODO add your handling code here:
    frmCargaAcademicaDocentes frmCarga = new frmCargaAcademicaDocentes(this,true);
    frmCarga.setLocationRelativeTo(this);
    frmCarga.setVisible(true);
}//GEN-LAST:event_jMenuItem4ActionPerformed

private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
// TODO add your handling code here:
    frmListaPagos frmpagos = new frmListaPagos(this, true);
    frmpagos.setLocationRelativeTo(this);
    frmpagos.setVisible(true);
}//GEN-LAST:event_jMenuItem9ActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {
            // TODO add your handling code here:
               frmConfiguracion frmconfiguracion=new frmConfiguracion(this,true);
               frmconfiguracion.setLocationRelativeTo(this);
               frmconfiguracion.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
 // TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_formWindowClosed

private void smnuRevasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuRevasActionPerformed
        try {
            // TODO add your handling code here:
               frmGenerarREVA frmreva =new frmGenerarREVA(this,false);
               frmreva.setLocationRelativeTo(this);
               frmreva.setTitle("GENERADOR DE REVAS");
               frmreva.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}//GEN-LAST:event_smnuRevasActionPerformed

private void smnuGestionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuGestionUsuariosActionPerformed
// TODO add your handling code here:
    frmUsuarios frmusuarios=new frmUsuarios(this,true);
    frmusuarios.setLocationRelativeTo(this);
    frmusuarios.setVisible(true);        
}//GEN-LAST:event_smnuGestionUsuariosActionPerformed

private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
// TODO add your handling code here:
    frmUsuarios frmusuarios=new frmUsuarios(this,true);
    frmusuarios.setLocationRelativeTo(this);
    frmusuarios.setVisible(true);    
}//GEN-LAST:event_jMenu7ActionPerformed

private void smnuBajasAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuBajasAlumnosActionPerformed
// TODO add your handling code here:
    frmBajasAlumnos fbajas = new frmBajasAlumnos(this,true);
    fbajas.setUsuario(sesion);
    fbajas.setLocationRelativeTo(this);
    fbajas.setVisible(true);
}//GEN-LAST:event_smnuBajasAlumnosActionPerformed

private void smnuModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuModulosActionPerformed
// TODO add your handling code here:
    frmModulos frmmodulos = new frmModulos(this,true);
    frmmodulos.setLocationRelativeTo(this);
    frmmodulos.setVisible(true);
}//GEN-LAST:event_smnuModulosActionPerformed

private void smnuUnidadAprendizajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuUnidadAprendizajeActionPerformed
// TODO add your handling code here:
    frmListaModulos frmlistamodulos = new frmListaModulos(this,true);
    frmlistamodulos.setLocationRelativeTo(this);
    frmlistamodulos.setVisible(true);
}//GEN-LAST:event_smnuUnidadAprendizajeActionPerformed

private void smnuAjusteCargaAcademicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuAjusteCargaAcademicaActionPerformed
// TODO add your handling code here:
//Ajuste de carga academica
try {
            // TODO add your handling code here:
               
               
               dlgBuscarAlumnoInscrito dlgbuscar=new dlgBuscarAlumnoInscrito(this,true);
               dlgbuscar.setLocationRelativeTo(this);
               dlgbuscar.setVisible(true);
               dlgbuscar.setUsuario(sesion);
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}//GEN-LAST:event_smnuAjusteCargaAcademicaActionPerformed

private void mnuReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReportesActionPerformed
// TODO add your handling code here:
//Reporte lista de asistencia

}//GEN-LAST:event_mnuReportesActionPerformed

private void smnuListaAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuListaAsistenciaActionPerformed
// TODO add your handling code here:
try {
            // TODO add your handling code here:
               
               frmGenerarListasAsistencias frmlistas=new frmGenerarListasAsistencias(this,false);
               frmlistas.setLocationRelativeTo(this);
               frmlistas.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        
}//GEN-LAST:event_smnuListaAsistenciaActionPerformed

private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jMenu8ActionPerformed

private void smnuCerrarSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuCerrarSemestreActionPerformed
// TODO add your handling code here:
    frmCerrarSemestre frmcerrar = new frmCerrarSemestre(this,true);
    frmcerrar.setLocationRelativeTo(this);
    frmcerrar.setVisible(true);
}//GEN-LAST:event_smnuCerrarSemestreActionPerformed

private void smnuparcialesmaestroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuparcialesmaestroActionPerformed
        try {
            // TODO add your handling code here:
                          frmRegistrarCalificacionesMaestro dlgcalificaciones=new frmRegistrarCalificacionesMaestro(this,true,sesion);
                          dlgcalificaciones.setLocationRelativeTo(this);
                          dlgcalificaciones.setUsuario(sesion);
                          dlgcalificaciones.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_smnuparcialesmaestroActionPerformed
private void vistaUsuario(int id_usuario) throws SQLException, ClassNotFoundException{
           int permiso;
            
            ctrlPermisosUsuario acceso = new ctrlPermisosUsuario();

            permiso = 10000; //Alumnos    
            if (acceso.permitido(id_usuario,permiso)){
                this.jMenu1.setVisible(true);               
                
                permiso = 10100; //Alta de Alumnos
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuRegistrar.setVisible(true);               
                }else{
                    this.smnuRegistrar.setVisible(false);
                }       
                
                permiso = 10200; //Kardex
                if (acceso.permitido(id_usuario,permiso)){
                    this.jMenuItem2.setVisible(true);               
                }else{
                    this.jMenuItem2.setVisible(false);
                }
                
                permiso = 10300; //Inscripciones-Reinscripciones
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuinscripciones.setVisible(true);               
                }else{
                    this.smnuinscripciones.setVisible(false);
                }
                
                permiso = 10400; //Bajas de Alumnos
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuBajasAlumnos.setVisible(true);               
                }else{
                    this.smnuBajasAlumnos.setVisible(false);               
                }

                permiso = 10500; //Ajuste de Carga Academica
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuAjusteCargaAcademica.setVisible(true);               
                }else{
                    this.smnuAjusteCargaAcademica.setVisible(false);               
                }
                
            }else{
                this.jMenu1.setVisible(false);
            }
            
            permiso = 20000; //Maestros    
            if (acceso.permitido(id_usuario,permiso)){
                this.jMenu2.setVisible(true); 

                permiso = 20100; //GestiÃ³n de Puestos
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuPuestos.setVisible(true);               
                }else{
                    this.smnuPuestos.setVisible(false);
                }       
                
                permiso = 20200; //GestiÃ³n de Maestros
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuPuestos.setVisible(true);               
                }else{
                    this.smnuPuestos.setVisible(false);
                }
                
                permiso = 20300; //AsignaciÃ³n de Carga AcadÃ©mica
                if (acceso.permitido(id_usuario,permiso)){
                    this.jMenuItem4.setVisible(true);               
                }else{
                    this.jMenuItem4.setVisible(false);
                }
                
                
            }else{
                this.jMenu2.setVisible(false);
            }

            permiso = 30000; //Grupos
            if (acceso.permitido(id_usuario,permiso)){
                this.mnuGrupos.setVisible(true);               
                
                permiso = 30100; //GestiÃ³n de Grupos
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuGestionGrupos.setVisible(true);               
                }else{
                    this.smnuGestionGrupos.setVisible(false);
                }       
                                        
            }else{
                this.mnuGrupos.setVisible(false);
            }

            permiso = 40000; //AdministraciÃ³n
            if (acceso.permitido(id_usuario,permiso)){
                this.jMenu4.setVisible(true);          
                
                permiso = 40100; //Ciclo Escolar
                if (acceso.permitido(id_usuario,permiso)){
                    this.jMenu8.setVisible(true);               
                }else{
                    this.jMenu8.setVisible(false);
                }       
                
                permiso = 40200; //GestiÃ³n de Carreras
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuCarreras.setVisible(true);               
                }else{
                    this.smnuCarreras.setVisible(false);
                }
                
                permiso = 40300; //GestiÃ³n de Planes
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuPlanes.setVisible(true);               
                }else{
                    this.smnuPlanes.setVisible(false);
                }

                permiso = 40400; //GestiÃ³n de Asignaturas
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuAsignaturas.setVisible(true);               
                }else{
                    this.smnuAsignaturas.setVisible(false);
                }
                
                permiso = 40500; //GestiÃ³n de Módulos
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuModulos.setVisible(true);               
                }else{
                    this.smnuModulos.setVisible(false);
                }
                
                permiso = 40600; //GestiÃ³n de Unidades de Aprendizaje
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuUnidadAprendizaje.setVisible(true);               
                }else{
                    this.smnuUnidadAprendizaje.setVisible(false);
                }
                
                
                        
            }else{
                this.jMenu4.setVisible(false);
            }
            
            permiso = 50000; //Calificaciones
            if (acceso.permitido(id_usuario,permiso)){
                this.jMenu5.setVisible(true);               

                permiso = 50100; //Registrar Calificaciones
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuRegistrarCalificaciones.setVisible(true);               
                }else{
                    this.smnuRegistrarCalificaciones.setVisible(false);
                }
                
            }else{
                this.jMenu5.setVisible(false);
            }

            permiso = 60000; //Cobranza
            if (acceso.permitido(id_usuario,permiso)){
                this.jMenu6.setVisible(true);               
                
                permiso = 60100; //Partidas
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuPartidas.setVisible(true);               
                }else{
                    this.smnuPartidas.setVisible(false);
                }

                permiso = 60200; //Pagos
                if (acceso.permitido(id_usuario,permiso)){
                    this.jMenuItem9.setVisible(true);               
                }else{
                    this.jMenuItem9.setVisible(false);
                }
                
            }else{
                this.jMenu6.setVisible(false);
            }

            permiso = 70000; //Reportes
            if (acceso.permitido(id_usuario,permiso)){
                
                this.mnuReportes.setVisible(true);
                
                permiso = 70100; //REVAs
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuRedis.setVisible(true);               
                }else{
                    this.smnuRedis.setVisible(false);
                }

                permiso = 70200; //REDIS
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuRevas.setVisible(true);               
                }else{
                    this.smnuRevas.setVisible(false);
                }
                
                permiso = 70300; //Lista de Asistencia
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuListaAsistencia.setVisible(true);               
                }else{
                    this.smnuListaAsistencia.setVisible(false);
                }

                permiso = 70400; //Rexas
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuRexas.setVisible(true);               
                }else{
                    this.smnuRexas.setVisible(false);
                }
                

            }else{
                this.mnuReportes.setVisible(false);
            }
            
            permiso = 80000; //ConfiguraciÃ³n
            if (acceso.permitido(id_usuario,permiso)){
                this.jMenu7.setVisible(true);               

                permiso = 80100; //Escuela
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuEscuela.setVisible(true);               
                }else{
                    this.smnuEscuela.setVisible(false);
                }

                permiso = 80200; //ParÃ¡metros de Reportes
                if (acceso.permitido(id_usuario,permiso)){
                    this.jMenuItem5.setVisible(true);               
                }else{
                    this.jMenuItem5.setVisible(false);
                }
                
                permiso = 80300; //ParÃ¡metros de Reportes
                if (acceso.permitido(id_usuario,permiso)){
                    this.smnuGestionUsuarios.setVisible(true);               
                }else{
                    this.smnuGestionUsuarios.setVisible(false);               
                }
                
            }else{
                this.jMenu7.setVisible(false);
            }

    
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu mnuGrupos;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenuItem smnuActivarCiclos;
    private javax.swing.JMenuItem smnuAjusteCargaAcademica;
    private javax.swing.JMenuItem smnuAsignaturas;
    private javax.swing.JMenuItem smnuBajasAlumnos;
    private javax.swing.JMenuItem smnuCarreras;
    private javax.swing.JMenuItem smnuCerrarSemestre;
    private javax.swing.JMenuItem smnuEscuela;
    private javax.swing.JMenuItem smnuGestionCiclos;
    private javax.swing.JMenuItem smnuGestionGrupos;
    private javax.swing.JMenuItem smnuGestionUsuarios;
    private javax.swing.JMenuItem smnuListaAsistencia;
    private javax.swing.JMenuItem smnuModulos;
    private javax.swing.JMenuItem smnuPartidas;
    private javax.swing.JMenuItem smnuPlanes;
    private javax.swing.JMenuItem smnuProfesores;
    private javax.swing.JMenuItem smnuPuestos;
    private javax.swing.JMenuItem smnuRedis;
    private javax.swing.JMenuItem smnuRegistrar;
    private javax.swing.JMenuItem smnuRegistrarCalificaciones;
    private javax.swing.JMenuItem smnuRevas;
    private javax.swing.JMenuItem smnuRexas;
    private javax.swing.JMenuItem smnuUnidadAprendizaje;
    private javax.swing.JMenuItem smnuinscripciones;
    private javax.swing.JMenuItem smnuparcialesmaestro;
    // End of variables declaration//GEN-END:variables
}
