/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jpfondo.java
 *
 * Created on 24-mar-2012, 0:31:43
 */
package Formularios;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Last Develop
 */
public class jpfondo extends javax.swing.JPanel {
private Image imagen=null;
    @Override
    public void paint(Graphics g) {
        if(imagen!=null)
        {
        g.drawImage(imagen, 0, 0,this.getWidth(),this.getHeight(),this);
        this.setOpaque(false);
        }
        else
        {
        this.setOpaque(true);
        }
        super.paint(g);
    }

public void setImagenNueva(Image imagennueva)
{
 this.imagen=imagennueva;
}

    public void setImagen(String nombreImagen) {
    if(nombreImagen!=null)    
    {
       imagen= new ImageIcon(nombreImagen).getImage();
       
    }
    else
        imagen=null;

    }

    public jpfondo(Image imagen) {
        if(imagen!=null)
            this.imagen=imagen;
        else
          this.imagen=null;      
    }

    /** Creates new form jpfondo */
    public jpfondo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
